// src/components/Navbar.vue
<script>
export default {
  name: 'Navbar',
  data() {
    return {
      isOpen: false,
    }
  },
  methods: {
    toggleMenu() {
      this.isOpen = !this.isOpen
    },
  },
}
</script>

<template>
  <nav class="bg-gray-800 bg-opacity-75 p-4 sticky top-0 z-50">
    <div class="container mx-auto flex justify-between items-center">
      <a href="#home" class="text-white text-2xl font-bold">Bandgeek.dev</a>
      <div class="block lg:hidden">
        <button @click="toggleMenu" class="text-gray-300 hover:text-white focus:outline-none">
          <svg
            class="h-6 w-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16m-7 6h7"
            ></path>
          </svg>
        </button>
      </div>
      <div
        :class="{ block: isOpen, hidden: !isOpen }"
        class="w-full lg:flex lg:items-center lg:w-auto"
      >
        <ul class="flex flex-col lg:flex-row lg:space-x-4">
          <li>
            <a
              href="#home"
              class="nav-link block py-2 px-3 text-gray-300 rounded transition duration-300 ease-in-out transform hover:bg-gray-100 hover:text-blue-700 hover:scale-105"
            >
              Home
            </a>
          </li>
          <li>
            <a
              href="#about"
              class="nav-link block py-2 px-3 text-gray-300 rounded transition duration-300 ease-in-out transform hover:bg-gray-100 hover:text-blue-700 hover:scale-105"
            >
              About
            </a>
          </li>
          <li>
            <a
              href="#projects"
              class="nav-link block py-2 px-3 text-gray-300 rounded transition duration-300 ease-in-out transform hover:bg-gray-100 hover:text-blue-700 hover:scale-105"
            >
              Projects
            </a>
          </li>
          <li>
            <a
              href="#contact"
              class="nav-link block py-2 px-3 text-gray-300 rounded transition duration-300 ease-in-out transform hover:bg-gray-100 hover:text-blue-700 hover:scale-105"
            >
              Contact
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<style scoped>
.nav-link {
  transition: transform 0.3s ease-in-out;
}

.nav-link:hover {
  transform: rotate(-5deg) scale(1.1);
}
</style>

// app/components/NavBar.tsx
"use client";
import { useState } from "react";

const NavBar = () => {
  const [menuOpen, setMenuOpen] = useState(false);

  // Toggle the dropdown menu on mobile
  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <div className="relative">
      <div className="navbar bg-white fixed top-0 left-0 right-0 z-10 shadow-md">
        <div className="flex-1">
          <a className="btn btn-ghost text-xl">My Portfolio</a>
        </div>

        {/* Desktop Navigation Links */}
        <div className="flex-none hidden lg:flex space-x-4">
          <a href="#home" className="btn btn-ghost text-base">
            Home
          </a>
          <a href="#about" className="btn btn-ghost text-base">
            About Me
          </a>
          <a href="#portfolio" className="btn btn-ghost text-base">
            Portfolio
          </a>
          <a href="#contact" className="btn btn-ghost text-base">
            Contact
          </a>
        </div>

        {/* Mobile Hamburger Icon */}
        <div className="flex-none lg:hidden">
          <button
            className="btn btn-square btn-ghost"
            onClick={toggleMenu} // Toggle dropdown visibility on mobile
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="h-6 w-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
              />
            </svg>
          </button>
        </div>
      </div>

      {/* Background Overlay for Darkening/Blurring (only when menu is open) */}
      {menuOpen && (
        <div className="fixed top-0 left-0 right-0 bottom-0 bg-black opacity-50 z-0"></div>
      )}

      {/* Mobile Dropdown Menu (Slide-in from the left) */}
      <div
        className={`lg:hidden fixed top-0 left-0 bottom-0 w-64 bg-white shadow-md transform ${
          menuOpen ? "translate-x-0" : "-translate-x-full"
        } transition-transform duration-300 ease-in-out z-50`} // z-50 ensures it's above everything
      >
        <div className="flex justify-end p-4">
          <button onClick={toggleMenu} className="text-xl">
            &times;
          </button>
        </div>
        <a href="#home" className="block px-4 py-2 text-base">
          Home
        </a>
        <a href="#about" className="block px-4 py-2 text-base">
          About Me
        </a>
        <a href="#portfolio" className="block px-4 py-2 text-base">
          Portfolio
        </a>
        <a href="#contact" className="block px-4 py-2 text-base">
          Contact
        </a>
      </div>

      {/* Dark Overlay between the menu and background */}
      {menuOpen && (
        <div className="lg:hidden fixed top-0 left-0 right-0 bottom-0 bg-black opacity-50 z-40"></div>
      )}
    </div>
  );
};

export default NavBar;
